default: &default
  GOOGLE_CLIENT_ID: <%= ENV.fetch("TASKKA_GOOGLE_CLIENT_ID") { nil } %>
  GOOGLE_CLIENT_SECRET: <%= ENV.fetch("TASKKA_GOOGLE_CLIENT_SECRET") { nil } %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
