default: &default
  GOOGLE_CLIENT_ID: <%= ENV.fetch("TASKKA_GOOGLE_CLIENT_ID") %>
  GOOGLE_CLIENT_SECRET: <%= ENV.fetch("TASKKA_GOOGLE_CLIENT_SECRET") %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
